webshop:
  target: dev
  outputs:
    dev:
      dbname: webshop
      schema: public
      host: localhost
      user: admin
      pass: admin
      port: 5432
      threads: 1
      type: postgres
    prod:
      dbname: webshop
      schema: public
      host: localhost
      user: admin
      pass: admin
      port: 2345
      threads: 1
      type: postgres
 
