name: CI_pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  CI_jobs: 
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      MINIO_ACCESS_KEY: ${{ secrets.POSTRES_DB }}
      GIT_SHA: 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      
      - name: Install Python
        run: uv python install
      
      - name: Install dependencies
        run: uv sync --group ci
    